const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const os = require("os");
const path = require("path");

const firstExisting = (candidates) =>
  candidates.find((candidate) => candidate && fs.existsSync(candidate));

const findAndroidSdk = () =>
  firstExisting([
    process.env.ANDROID_HOME,
    process.env.ANDROID_SDK_ROOT,
    process.platform === "darwin"
      ? path.join(os.homedir(), "Library", "Android", "sdk")
      : undefined,
    process.platform === "linux" ? path.join(os.homedir(), "Android", "Sdk") : undefined,
    process.platform === "linux" ? "/opt/android-sdk" : undefined,
    process.platform === "win32" && process.env.LOCALAPPDATA
      ? path.join(process.env.LOCALAPPDATA, "Android", "Sdk")
      : undefined,
  ]);

const findAndroidJdk = () =>
  firstExisting([
    process.env.ANDROID_JAVA_HOME,
    process.platform === "darwin"
      ? "/Applications/Android Studio.app/Contents/jbr/Contents/Home"
      : undefined,
    process.platform === "linux" ? "/opt/android-studio/jbr" : undefined,
    process.platform === "win32" && process.env.ProgramFiles
      ? path.join(process.env.ProgramFiles, "Android", "Android Studio", "jbr")
      : undefined,
    process.env.JAVA_HOME,
  ]);

const escapePropertyValue = (value) => value.replaceAll("\\", "\\\\").replaceAll(":", "\\:");

/**
 * Writes machine-local Android SDK and JDK paths during Expo prebuild.
 * Override discovery with ANDROID_HOME and ANDROID_JAVA_HOME respectively.
 */
const withAndroidLocalProperties = (config) =>
  withDangerousMod(config, [
    "android",
    async (config) => {
      const androidRoot = config.modRequest.platformProjectRoot;
      const sdkDir = findAndroidSdk();
      const javaHome = findAndroidJdk();

      if (!sdkDir) {
        throw new Error(
          "Android SDK not found. Set ANDROID_HOME or ANDROID_SDK_ROOT before running Expo prebuild.",
        );
      }

      if (!javaHome) {
        throw new Error(
          "Android JDK not found. Install Android Studio or set ANDROID_JAVA_HOME to JDK 21.",
        );
      }

      fs.writeFileSync(
        path.join(androidRoot, "local.properties"),
        `sdk.dir=${escapePropertyValue(sdkDir)}\n`,
      );

      const gradlePropertiesPath = path.join(androidRoot, "gradle.properties");
      const javaHomeProperty = `org.gradle.java.home=${escapePropertyValue(javaHome)}`;
      const gradleProperties = fs.readFileSync(gradlePropertiesPath, "utf8");
      const nextGradleProperties = /^org\.gradle\.java\.home=.*$/m.test(gradleProperties)
        ? gradleProperties.replace(/^org\.gradle\.java\.home=.*$/m, javaHomeProperty)
        : `${gradleProperties.trimEnd()}\n\n# Generated by withAndroidLocalProperties\n${javaHomeProperty}\n`;

      fs.writeFileSync(gradlePropertiesPath, nextGradleProperties);
      return config;
    },
  ]);

module.exports = withAndroidLocalProperties;
